
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret_sanata-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: secret_santa
  template:
    metadata:
      labels:
        app: sectret_sanata
    spec:
      containers:
        - name: tetris
          image: felix081/santa:latest # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on

