
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: public.ecr.aws/l8l8e3n1/nextcloudapp:nextcloudappv1.1 # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on

