
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: secret-santa
  template:
    metadata:
      labels:
        app: secret-santa
    spec:
      containers:
        - name: secret-santa
          image: felix081/santa:latest # Replace with the actual image tag
          ports:
            - containerPort: 8080 # Replace with the port your Tetris game listens on

